services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
  react-app:
    build:
      context: ./floma_docs_app
    ports:
      - "3000:3000"
    volumes:
      - ./floma_docs_app:/app
    command: yarn start